<a href="https://colab.research.google.com/github/SubhashMurmu/learning_stuff/blob/main/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

//to fill in the tensor x

In [3]:
x.numel()

12

//no of elements in the tensor

In [4]:
x.shape

torch.Size([12])

// to get dimension and size

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

//(row , column)   
// given a tensor of size n and target (h,w), we know that w=n/h.
// if(soemthing , -1) then -1 denotes the above calculation done by the torch library

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

// to make all zeroes

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

// make all ones

In [9]:
torch.randn(3,4)

tensor([[-0.5624,  0.8752,  0.2645, -0.4415],
        [-0.0355,  0.0348, -0.1614,  0.8813],
        [ 1.2393,  0.5541,  0.6423, -0.2256]])

//random numbers from gaussian distribution

In [10]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

//making my own custom tensor

In [13]:
X[-1] , X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

// slicing operation

In [14]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

//indexing

In [15]:
X[:2 , : ] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

(row slicing, column slicing)

In [18]:
torch.exp(x)


tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [19]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
x+y , x-y , x*y , x/y ,x**y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [20]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y) , dim = 0 ) , torch.cat((X,Y) , dim = 1 )

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

//torch.cat((X, Y), dim=0) → Concatenate along rows (vertical stack)
//torch.cat((X, Y), dim=1) → Concatenate along columns (horizontal stack)

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

//compare

In [22]:
X.sum()

tensor(66.)

In [23]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

//Since a and b are 3 × 1 and 1 × 2 matrices, respectively, their shapes do not match up.
Broadcasting produces a larger 3 × 2 matrix by replicating matrix a along the columns and
matrix b along the rows beore adding them elementwise.

In [30]:
before = id(Y)
Y = Y + X
id(Y) == before

False